name: Test

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
      - cron: '0 15 * * *'

env:
  CI: true

jobs:


  lin-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:

    - uses: actions/checkout@v2

    - run: docker run --rm -v $(pwd):/src -w /src -e CI ghdl/vunit:mcode-master python3 -m pytest -v -s -ra test.py --color=yes


  lin-setup:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: python -m pip install --progress-bar off pytest

    - run: python -m pytest -v -s -ra test.py --color=yes


  win-setup:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true

    - uses: actions/checkout@v2

    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm
    - run: python -m pip install --progress-bar off pytest

    - run: python -m pytest -v -s -ra test.py --color=yes
